name: Cloud Functions Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: api/functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: api/functions/lib
      - name: Archive Firebase config
        uses: actions/upload-artifact@v2
        with:
          name: firebase
          path: |
            api/.firebaserc
            api/firebase.json

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib
      - name: Download Firebase Artifact
        uses: actions/download-artifact@v2
        with:
          name: firebase
      - name: Deploy to Firebase
        uses: wib-wub/deploy-firebase-functions@1.0.1
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}