name: Cloud Functions Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: api/functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      # Deploying the functions to firebase
      - name:  Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}