name: Firebase Deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        env:
          CI: true
        run: npm test
      - name: Build
        run: npm run build
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: app/build
      - name: Archive Firebase config
        uses: actions/upload-artifact@v2
        with:
          name: firebase
          path: |
            app/.firebaserc
            app/firebase.json

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Download Firebase Artifact
        uses: actions/download-artifact@v2
        with:
          name: firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}